# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            FileOperations
tagline:          'A Python Library'
description:      'A Python Library to perform various file operations'
url:              http://github.com/hassaanaliw/fileoperations
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.1.0

github:
  repo:           http://github.com/hassaanaliw/fileoperations
